### ISSUE TITLE
Tags on individual unchanged LU's are spread across the whole matching rule

### ISSUE THREAD

**Issue by TinoDidriksen** [apertium/apertium-separable#49]
`echo 'Hos personer med <a class="crossref" href="https://sml.snl.no/atopisk_eksem">atopisk eksem</a> foreligger ofte arvelige faktorer' | apertium -u -f html-noent nob-nno_e`

Output after `apertium-pretransfer -z`:
```
^hos<pr><Aa><@adv>$
^person<n><m><pl><ind><aa><@←p-utfyll>$
^med<pr><aa><@adv>$
[[t:a:_3bPiw]]^atopisk<adj><pst><nt><sg><ind><aa><@adj→>$
[[t:a:_3bPiw]]^eksem<n><nt><sg><ind><aa><@←p-utfyll>$
^foreligge<vblex><pres><aa><@fv>$
^ofte<adv><aa><@adv>$
^arvelig<adj><pst><un><pl><ind><aa><@adj→>$
^faktor<n><m><pl><ind><aa><@subj>$^.<sent><clb><aa>$[]
```

Output after `lsx-proc -z -w 'nob-nno.autoseq.bin'`:
```
^hos<pr><Aa><@adv>$
^person<n><m><pl><ind><aa><@←p-utfyll>$
[[t:a:_3bPiw; t:a:_3bPiw]]^med<pr><aa><@adv>$
[[t:a:_3bPiw; t:a:_3bPiw]]^atopisk<adj><pst><nt><sg><ind><aa><@adj→>$
[[t:a:_3bPiw; t:a:_3bPiw]]^eksem<n><nt><sg><ind><aa><@←p-utfyll>$
[[t:a:_3bPiw; t:a:_3bPiw]]^ligge<vblex><pres><aa><@fv>$
[[t:a:_3bPiw; t:a:_3bPiw]]^ofte<adv><aa><@adv>$
[[t:a:_3bPiw; t:a:_3bPiw]]^arvelig<adj><pst><un><pl><ind><aa><@adj→>$
[[t:a:_3bPiw; t:a:_3bPiw]]^faktor<n><m><pl><ind><aa><@subj>$
[[t:a:_3bPiw; t:a:_3bPiw]]^fore<adv>$^.<sent><clb><aa>$[]
```

**Comment by mr-martian** [comment]
Runtime might not actually be a bad idea. We could check if any of the output words are identical to any of the input words, and if they are, then they only get the wblank of that input word. This only becomes a problem if it turns out to be noticeably slower or if the input contains multiple identical words. Arguably there's an issue if the rule deletes a word and creates another one that happens to be identical, but I think we can just count that as moving it.
